### ISSUE TITLE
How to test on Tsinghua-Daimler Dataset

### ISSUE THREAD

**Issue by leonzfa** [thanif/Camera-Calibration-through-Camera-Projection-Loss#1]
Hi,
It seems that there is not right images in the Tsinghua-Daimler Dataset. How do you perform experiments on this dataset?

**Comment by thanif** [comment]
Hi,

I have used the following formula for generating the right images.

Basically, left - disparity = right

rightImg = np.array(leftImg) - np.array(dspimg)

You can see it in Data_Preparation/data_preparation.ipynb
