### ISSUE TITLE
Issue of standards

### ISSUE THREAD

**Issue by KungZell** [thanif/Camera-Calibration-through-Camera-Projection-Loss#2]
Hello， @thanif  
Thank you for your open source project
I have some questions about this project. How should this project be deployed? Is multi-camera calibration implemented?

**Comment by thanif** [comment]
I have not deployed it. The dataset contains multiple camera configurations.

**Comment by lovejoker1102** [comment]
Do you know the DTU dataset? I want to use this dataset and calibrate the camera, can I use this project?

**Comment by thanif** [comment]
Hi, I have not used DTU dataset.
