### ISSUE TITLE
Data from the wild

### ISSUE THREAD

**Issue by BrianG13** [thanif/Camera-Calibration-through-Camera-Projection-Loss#3]
Hi,
Can you publish some instructions how to use the model with data from the wild?
I have a pair of images and want to use the network for camera extrinsics estimation, how can I do it?

**Comment by thanif** [comment]
You have to provide all the parameters required by the model including both intrinsic and extrinsic along with baseline and disparity. Once you have the parameters, you can save them as npy files. Use the code as it is. It should work.

**Comment by BrianG13** [comment]
The model doesn't predict the extrinsic parameters ?

**Comment by thanif** [comment]
The model provides intrinsic parameters.

**Comment by thanif** [comment]
The model provides both intrinsic and extrinsic parameters. It predicts translation in x,y and z axis while only Pitch for rotation. Yaw and Roll are not included.

**Comment by lovejoker1102** [comment]
If I only have images, can I get the in and ex parameters of the camera through the network?

**Comment by thanif** [comment]
Yes, if you have only images, you can get both intrinsic and extrinsic
parameters using the network

**Comment by lovejoker1102** [comment]
Thanks for your reply! And I have another question, I can only use two images at once, right? If I have 50 images, can I get their camera parameters together?

**Comment by thanif** [comment]
No. By two, what it means is that one left image and one right image. If
you have 50 pairs, you can get 50 results at once.
