### ISSUE TITLE
ValueError: The name "mixed0" is used 2 times in the model

### ISSUE THREAD

**Issue by BrianG13** [thanif/Camera-Calibration-through-Camera-Projection-Loss#4]
I am trying to run the jupyter notebook (without any change).

But I have the following error:
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/51123168/174814584-2b19eef0-9b2b-4169-b59a-7c6e73e594c8.png">

It happens across all the notebooks.
Which tensorflow version are you using?

**Comment by thanif** [comment]
It's not because of version mismatch. It's about resnet being used multiple
times. You should change the layer names in base code of the resnet.

**Comment by thanif** [comment]
Sorry, it's not resnet. Its inception-v3.

**Comment by Pppapaya** [comment]
Hi, I met this issue too. Do you fix that? Would you mind guiding me with that?

**Comment by CMakey** [comment]
for others who don't know how to solve this question [https://github.com/keras-team/keras/issues/7412#issuecomment-896367882](url)
