### ISSUE TITLE
model.load error

### ISSUE THREAD

**Issue by Pppapaya** [thanif/Camera-Calibration-through-Camera-Projection-Loss#7]
Hello, thank you for sharing such impressive work. I'm new for this topic. I'd like to ask that can I use any two pictures as left and right inputs to get internal and external parameters? Also, for running the provided code, do I need to recompile the model? Because when I write the test file as my self, it shows error when I use model.load directly. Please guide me with it! Looking forward to your reply! Thanks!

**Comment by thanif** [comment]
Hi,

Yes, you can use any two pictures as left and right inputs to get internal and external parameters. Yes, I think you need to recompile the model.

**Comment by Pppapaya** [comment]
Ok, thank you for your help. By the way, is it only suitable for 112*112, do you consider to expand it in future? Looking forward to your results!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thanif** [comment]
Hi,

Yes, currently, it is only suitable for 112x112, I currently don't have any plans to expand it but as the code is available, anybody can do it if it is required.

**Comment by xz0613** [comment]
"ValueError: The name "mixed0" is used 2 times in the model. All layer names should be unique."
Do you have such a problem or can you suggest a solution, I can't solve it

**Comment by thanif** [comment]
Hi,

The issue has been addressed here: https://github.com/thanif/CPL/issues/4
