### ISSUE TITLE
question about input of model at inference time

### ISSUE THREAD

**Issue by hrz2000** [thanif/Camera-Calibration-through-Camera-Projection-Loss#8]
can i use just one image and repeat it as left image and right image to get ins and exts of the camera? i'm a newer, why we need a pair of images?

**Comment by thanif** [comment]
Hi,

Yes, you can get the parameters by repeating an image. So, we need a pair because we cant predict extrinsic parameters from a single image. Using repeated image, the model will give some output but to what extent it would be correct that needs to be checked.

**Comment by hrz2000** [comment]
thanks for your timely reply！
